# Generated by Django 5.0.6 on 2024-09-22 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fabricOrderManagement", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fabricorder",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="fabricorder",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="fabricorderitem",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="fabricorderitem",
            name="updated_by",
        ),
    ]
